# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/my_first_web"

# 网页的标题
title: "海来尔子"
username: 海来尔子
# 网站副标题
description: "强棒少女的陪伴日记"

aboutme: "我要唱响生活"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
